import P10S2Tests.Catalogue

/-!
# P10S2Tests.Gen — vector generator (vector side; outside the verifier manifest)

`lake env lean --run P10S2Tests/Gen.lean <verifier-manifest-digest-hex>` (reads `profile/LeafEncodeV0_SPEC.md`) writes, for every
catalogue entry, `vectors/<id>/{pB.json,inst.bin,tB.bin,iB.json,expected.txt}` and the Lean test
module `P10S2Tests/V_<id>.lean`, plus `vectors/INDEX.tsv`. Bytes are produced by the checker's
own codecs (the codec laws are theorems); the Lean tests then check the checker against the
expectations written in `Catalogue.lean`.
-/

open P10S2 P10S2Tests P10.Sha256

def toBA (l : List Nat) : ByteArray := ⟨(l.map Nat.toUInt8).toArray⟩

def hexStr (l : List Nat) : String := String.ofList ((P10S2.hexOf l).map Char.ofNat)

def writeBytes (path : System.FilePath) (l : List Nat) : IO Unit := IO.FS.writeBinFile path (toBA l)

def header (v : VectorSpec) (what : String) (tail : String) : String :=
  let d := s!"vectors/{v.id}"
  s!"import P10S2Tests.Common\n\n/-! Vector {v.id} ({v.prereg}){what}. GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_{v.id}{tail}\nopen P10S2 P10S2Tests\n\ndef pB : Bytes := filebytes% \"{d}/pB.json\"\ndef instB : Bytes := filebytes% \"{d}/inst.bin\"\ndef inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)\n"

/-- Main module: the coverage outcome of the vector (one kernel evaluation). -/
def moduleText (v : VectorSpec) : String :=
  let d := s!"vectors/{v.id}"
  let body := match v.T with
    | some _ =>
      s!"def tB : Bytes := filebytes% \"{d}/tB.bin\"\n\ntheorem outcome : run pB instB tB = some ({v.expect}) := by decide +kernel\n"
    | none =>
      s!"\ntheorem outcome : runMissing pB instB = some ({v.expect}) := by decide +kernel\n"
  let extra := if v.e2e.isNone && !v.extra.isEmpty then "\n" ++ v.extra else ""
  header v "" "" ++ body ++ extra ++ s!"\nend V_{v.id}\n"

/-- The end-to-end composition is split over three modules so that no kernel evaluation holds the
whole SHA-256 workload (each evaluation needs several GB): `V_<id>` (coverage outcome),
`V_<id>_dig` (transcript digest) and `V_<id>_e2e` (rewriting with both results; only the small S1
part is evaluated). -/
def digModuleText (v : VectorSpec) (tHex : String) : String :=
  s!"import P10S2Tests.V_{v.id}\n\n/-! Vector {v.id} transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_{v.id}_dig\nopen P10S2 P10S2Tests V_{v.id}\n\ndef tDigest : Bytes := hex% \"{tHex}\"\n\ntheorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel\n\nend V_{v.id}_dig\n"

def e2eModuleText (v : VectorSpec) (_tHex : String) (ex : String) : String :=
  let d := s!"vectors/{v.id}"
  let ev := v.expect.drop 8
  s!"import P10S2Tests.V_{v.id}\nimport P10S2Tests.V_{v.id}_dig\n\n/-! Vector {v.id} (prereg {v.prereg}) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_{v.id}_e2e\nopen P10S2 P10S2Tests V_{v.id} V_{v.id}_dig\n\ndef iB : Bytes := filebytes% \"{d}/iB.json\"\n\ndef T : Transcript FxItem := (decodeTranscript fxItemC tB).get (by decide +kernel)\n\ntheorem hT : decodeTranscript fxItemC tB = some T := (Option.some_get _).symm\n\ntheorem hI : decodeInst instB = some inst := (Option.some_get _).symm\n\ntheorem hC : coverageCheck fx inst pB T = ({v.expect} : CoverageOutcome P10.S1.Evidence) := by\n  have h := outcome\n  unfold run at h\n  rw [hI, hT] at h\n  simp only [Option.bind_some] at h\n  exact Option.some.inj h\n\ntheorem e2e_outcome : runE2E tDigest tB pB iB instB = {ex} := by\n  have h1 := runE2E_of_inst (tDigest := tDigest) (tB := tB) (pB := pB) (iB := iB) hI\n  have h2 := e2eCheck_of_parts (iB := iB) hDig hT hC\n  have h3 : (match P10.Wire.decode iB with\n      | none => none\n      | some si =>\n        if (decide (si.evidence = {ev}) && decide (claimDigestV0 si.claim = inst.claimDigest) &&\n            P10.Wire.check iB) = true then some (({ev} : P10.S1.Evidence), si.claim) else none) = {ex} := by\n    decide +kernel\n  exact h1.trans (h2.trans h3)\n" ++
    (if v.extra.isEmpty then "" else "\n" ++ v.extra) ++ s!"\nend V_{v.id}_e2e\n"

/-- Differential vectors: the expected bytes are produced by independent Python tooling
(`scripts/s2a.py gen-differential`, using the frozen S1 `p10tool` JCS) and checked by the kernel. -/
def d1Text : String :=
  "import P10S2Tests.Common\n\n/-! Vector D1 (S2-D1, B6 and B1). GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_D1\nopen P10S2 P10S2Tests\n\ndef claimExp : Bytes := filebytes% \"vectors/D1/claim_digest.bin\"\ndef evidenceExp : Bytes := filebytes% \"vectors/D1/evidence_digest.bin\"\n\ntheorem claim : (claimDigestV0 P10.S1.Claim.secondBit).bytes = claimExp := by decide +kernel\n\ntheorem evidence :\n    (evidenceDigestV0 (P10.Wire.evidenceTok (P10.S1.Evidence.obs false (some false)))).bytes =\n      evidenceExp := by decide +kernel\n\nend V_D1\n"

def d2Text : String :=
  "import P10S2Tests.Common\n\n/-! Vector D2 (G6-B3). GENERATED by P10S2Tests.Gen; do not edit.\n`formula`: the Lean definition is exactly the gated formula. `empty` and `small` are kernel differentials against independent Python (hashlib) on small inputs (1 and 2 SHA-256 blocks; the second crosses a block boundary). The digest of the real 5.7 KB spec file is checked by `scripts/s2a.py leafspec` (independent Python), not by the kernel: its size would decide whether the acceptance command fits a runner. -/\nnamespace V_D2\nopen P10S2 P10S2Tests\n\ntheorem formula (f : Bytes) :\n    (leafEncodeSpecArtifactDigestV0 f).bytes =\n      P10.Sha256.sha256 (bytes% \"P10-LeafEncodeSpecArtifact-v0:\" ++ bytes% \"text-markdown-utf-8-v0:\" ++ f) := rfl\n\ndef expEmpty : Bytes := filebytes% \"vectors/D2/empty_digest.bin\"\ndef expSmall : Bytes := filebytes% \"vectors/D2/small_digest.bin\"\n\ntheorem empty : (leafEncodeSpecArtifactDigestV0 []).bytes = expEmpty := by decide +kernel\n\ntheorem small : (leafEncodeSpecArtifactDigestV0 (bytes% \"# LeafEncodeV0\\n\")).bytes = expSmall := by decide +kernel\n\nend V_D2\n"

/-- Differential vectors K1-K7 (prereg v0.2.6, K-1): `PreclosureDigestV0` on fixed views, with
expected bytes from independent Python JCS; K8 checks all seven together. -/
def kViews : List (String × String) :=
  let o := "⟨bytes% \"owner\"⟩"
  let a := "⟨bytes% \"admitter-a\"⟩"
  let b := "⟨bytes% \"admitter-b\"⟩"
  [("K1", "[]"),
   ("K2", s!"[(0, Kind.profileCommit, {o})]"),
   ("K3", s!"[(1, Kind.instanceCommit, {o})]"),
   ("K4", s!"[(2, Kind.admission, {a})]"),
   ("K5", s!"[(3, Kind.closure, {o})]"),
   ("K6", s!"[(4, Kind.adjudication, {o})]"),
   ("K7", s!"[(0, Kind.profileCommit, {o}), (7, Kind.instanceCommit, {o}), (10, Kind.admission, {a}), (123, Kind.admission, {b})]")]

def kText (id view : String) : String :=
  s!"import P10S2Tests.Common\n\n/-! Vector {id} (S2-{id}, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_{id}\nopen P10S2 P10S2Tests\n\ndef exp : Bytes := filebytes% \"vectors/{id}/digest.bin\"\n\ntheorem digest : (preclosureDigestV0 {view}).bytes = exp := by decide +kernel\n\nend V_{id}\n"

def k8Text : String :=
  let views := String.intercalate ",\n    " (kViews.map (·.2))
  let exps := String.intercalate ", " (kViews.map fun (id, _) => s!"(filebytes% \"vectors/{id}/digest.bin\" : Bytes)")
  s!"import P10S2Tests.Common\n\n/-! Vector K8 (S2-K8): Lean `PreclosureDigestV0` on K1-K7 equals the independent Python values. GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_K8\nopen P10S2 P10S2Tests\n\ndef views : List (List (Nat × Kind × Iss)) :=\n  [{views}]\n\ndef exps : List Bytes := [{exps}]\n\ntheorem all : views.map (fun v => (preclosureDigestV0 v).bytes) = exps := by decide +kernel\n\nend V_K8\n"

def main (args : List String) : IO UInt32 := do
  let some mdHex := args.head? | IO.eprintln "usage: Gen <manifest-digest-hex>"; return 2
  let mdBytes := mdHex.toList.map Char.toNat
  if h : allTokB mdBytes = true then
    let md : Tok := ⟨mdBytes, h⟩
    let specBytes := (← IO.FS.readBinFile "profile/LeafEncodeV0_SPEC.md").toList.map UInt8.toNat
    let lsBytes := (P10S2.hexOf (leafEncodeSpecArtifactDigestV0 specBytes).bytes)
    let lsO : Option Tok := if h2 : allTokB lsBytes = true then some ⟨lsBytes, h2⟩ else none
    let some ls := lsO | IO.eprintln "leaf spec digest is not a token"; return 2
    let mut index := "id\tprereg\tcondition\tlean\ttb7\n"
    for v in catalogue md ls do
      let dir : System.FilePath := s!"vectors/{v.id}"
      IO.FS.createDirAll dir
      writeBytes (dir / "pB.json") v.pB
      writeBytes (dir / "inst.bin") (cInstanceCommitment.enc v.inst)
      let mut tHex : Option String := none
      if let some T := v.T then
        let tB := encodeTranscript fxItemC T
        writeBytes (dir / "tB.bin") tB
        tHex := some (hexStr (sha256 tB))
      if let some iB := v.iB then writeBytes (dir / "iB.json") iB
      let tb7 := v.tb7.getD "-"
      IO.FS.writeFile (dir / "expected.txt")
        s!"id: {v.id}\nprereg: {v.prereg}\ncondition: {v.cond}\nlean: {v.expect}\ntb7: {tb7}\ne2e: {v.e2e.getD "-"}\nnote: {v.note}\n"
      IO.FS.writeFile s!"P10S2Tests/V_{v.id}.lean" (moduleText v)
      match v.iB, v.e2e, tHex with
      | some _, some ex, some h =>
        IO.FS.writeFile s!"P10S2Tests/V_{v.id}_dig.lean" (digModuleText v h)
        IO.FS.writeFile s!"P10S2Tests/V_{v.id}_e2e.lean" (e2eModuleText v h ex)
      | _, _, _ => pure ()
      index := index ++ s!"{v.id}\t{v.prereg}\t{v.cond}\t{v.expect}\t{tb7}\n"
    let kMods := (kViews.map fun (id, v) => (id, s!"S2-{id} (K-1)", kText id v)) ++ [("K8", "S2-K8 (K-1)", k8Text)]
    for (id, pre, txt) in [("D1", "S2-D1", d1Text), ("D2", "G6-B3 (leaf spec artifact digest)", d2Text)] ++ kMods do
      IO.FS.createDirAll s!"vectors/{id}"
      IO.FS.writeFile s!"vectors/{id}/expected.txt"
        s!"id: {id}\nprereg: {pre}\ncondition: differential\nlean: equal\ntb7: -\ne2e: -\nnote: expected bytes from scripts/s2a.py gen-differential\n"
      IO.FS.writeFile s!"P10S2Tests/V_{id}.lean" txt
      index := index ++ s!"{id}\t{pre}\tdifferential\tequal\t-\n"
    IO.FS.writeFile "vectors/INDEX.tsv" index
    IO.println s!"generated {(catalogue md ls).length + 2 + kMods.length} vectors"
    return 0
  else
    IO.eprintln "manifest digest must be a token (hex)"
    return 2
