import P10S2Tests.Catalogue

/-!
# P10S2Tests.Gen — vector generator (vector side; outside the verifier manifest)

`lake env lean --run P10S2Tests/Gen.lean <verifier-manifest-digest-hex>` writes, for every
catalogue entry, `vectors/<id>/{pB.json,inst.bin,tB.bin,iB.json,expected.txt}` and the Lean test
module `P10S2Tests/V_<id>.lean`, plus `vectors/INDEX.tsv`. Bytes are produced by the checker's
own codecs (the codec laws are theorems); the Lean tests then check the checker against the
expectations written in `Catalogue.lean`.
-/

open P10S2 P10S2Tests P10.Sha256

def toBA (l : List Nat) : ByteArray := ⟨(l.map Nat.toUInt8).toArray⟩

def hexDigit (n : Nat) : Char := "0123456789abcdef".toList.getD n '0'

def hexOf (l : List Nat) : String :=
  String.ofList (l.flatMap fun n => [hexDigit (n / 16 % 16), hexDigit (n % 16)])

def writeBytes (path : System.FilePath) (l : List Nat) : IO Unit := IO.FS.writeBinFile path (toBA l)

def moduleText (v : VectorSpec) (tHex : Option String) : String :=
  let d := s!"vectors/{v.id}"
  let ns := s!"V_{v.id}"
  let head := s!"import P10S2Tests.Common\n\n/-! Vector {v.id} ({v.prereg}). GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace {ns}\nopen P10S2 P10S2Tests\n\ndef pB : Bytes := filebytes% \"{d}/pB.json\"\ndef instB : Bytes := filebytes% \"{d}/inst.bin\"\ndef inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)\n"
  let body := match v.T with
    | some _ =>
      s!"def tB : Bytes := filebytes% \"{d}/tB.bin\"\n\ntheorem outcome : run pB instB tB = some ({v.expect}) := by decide +kernel\n"
    | none =>
      s!"\ntheorem outcome : runMissing pB instB = some ({v.expect}) := by decide +kernel\n"
  let e2e := match v.iB, v.e2e, tHex with
    | some _, some ex, some h =>
      s!"\ndef iB : Bytes := filebytes% \"{d}/iB.json\"\ndef tDigest : Bytes := hex% \"{h}\"\n\ntheorem e2e_outcome : runE2E tDigest tB pB iB instB = {ex} := by decide +kernel\n"
    | _, _, _ => ""
  head ++ body ++ e2e ++ (if v.extra.isEmpty then "" else "\n" ++ v.extra) ++ s!"\nend {ns}\n"

def main (args : List String) : IO UInt32 := do
  let some mdHex := args.head? | IO.eprintln "usage: Gen <manifest-digest-hex>"; return 2
  let mdBytes := mdHex.toList.map Char.toNat
  if h : allTokB mdBytes = true then
    let md : Tok := ⟨mdBytes, h⟩
    let mut index := "id\tprereg\tcondition\tlean\ttb7\n"
    for v in catalogue md do
      let dir : System.FilePath := s!"vectors/{v.id}"
      IO.FS.createDirAll dir
      writeBytes (dir / "pB.json") v.pB
      writeBytes (dir / "inst.bin") (cInstanceCommitment.enc v.inst)
      let mut tHex : Option String := none
      if let some T := v.T then
        let tB := encodeTranscript fxItemC T
        writeBytes (dir / "tB.bin") tB
        tHex := some (hexOf (sha256 tB))
      if let some iB := v.iB then writeBytes (dir / "iB.json") iB
      let tb7 := v.tb7.getD "-"
      IO.FS.writeFile (dir / "expected.txt")
        s!"id: {v.id}\nprereg: {v.prereg}\ncondition: {v.cond}\nlean: {v.expect}\ntb7: {tb7}\ne2e: {v.e2e.getD "-"}\nnote: {v.note}\n"
      IO.FS.writeFile s!"P10S2Tests/V_{v.id}.lean" (moduleText v tHex)
      index := index ++ s!"{v.id}\t{v.prereg}\t{v.cond}\t{v.expect}\t{tb7}\n"
    IO.FS.writeFile "vectors/INDEX.tsv" index
    IO.println s!"generated {(catalogue md).length} vectors"
    return 0
  else
    IO.eprintln "manifest digest must be a token (hex)"
    return 2
