import P10S2Tests.Catalogue

/-!
# P10S2Tests.Gen — vector generator (vector side; outside the verifier manifest)

`lake env lean --run P10S2Tests/Gen.lean <verifier-manifest-digest-hex>` (reads `profile/LeafEncodeV0_SPEC.md`) writes, for every
catalogue entry, `vectors/<id>/{pB.json,inst.bin,tB.bin,iB.json,expected.txt}` and the Lean test
module `P10S2Tests/V_<id>.lean`, plus `vectors/INDEX.tsv`. Bytes are produced by the checker's
own codecs (the codec laws are theorems); the Lean tests then check the checker against the
expectations written in `Catalogue.lean`.
-/

open P10S2 P10S2Tests P10.Sha256

def toBA (l : List Nat) : ByteArray := ⟨(l.map Nat.toUInt8).toArray⟩

def hexStr (l : List Nat) : String := String.ofList ((P10S2.hexOf l).map Char.ofNat)

def writeBytes (path : System.FilePath) (l : List Nat) : IO Unit := IO.FS.writeBinFile path (toBA l)

def header (v : VectorSpec) (what : String) (tail : String) : String :=
  let d := s!"vectors/{v.id}"
  s!"import P10S2Tests.Common\n\n/-! Vector {v.id} ({v.prereg}){what}. GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_{v.id}{tail}\nopen P10S2 P10S2Tests\n\ndef pB : Bytes := filebytes% \"{d}/pB.json\"\ndef instB : Bytes := filebytes% \"{d}/inst.bin\"\ndef inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)\n"

/-- Main module: the coverage outcome of the vector (one kernel evaluation). -/
def moduleText (v : VectorSpec) : String :=
  let d := s!"vectors/{v.id}"
  let body := match v.T with
    | some _ =>
      s!"def tB : Bytes := filebytes% \"{d}/tB.bin\"\n\ntheorem outcome : run pB instB tB = some ({v.expect}) := by decide +kernel\n"
    | none =>
      s!"\ntheorem outcome : runMissing pB instB = some ({v.expect}) := by decide +kernel\n"
  let extra := if v.e2e.isNone && !v.extra.isEmpty then "\n" ++ v.extra else ""
  header v "" "" ++ body ++ extra ++ s!"\nend V_{v.id}\n"

/-- Separate module for the end-to-end composition (kept apart to bound kernel memory). -/
def e2eModuleText (v : VectorSpec) (tHex : String) (ex : String) : String :=
  let d := s!"vectors/{v.id}"
  header v " end-to-end" "_e2e" ++
    s!"def tB : Bytes := filebytes% \"{d}/tB.bin\"\ndef iB : Bytes := filebytes% \"{d}/iB.json\"\ndef tDigest : Bytes := hex% \"{tHex}\"\n\ntheorem e2e_outcome : runE2E tDigest tB pB iB instB = {ex} := by decide +kernel\n" ++
    (if v.extra.isEmpty then "" else "\n" ++ v.extra) ++ s!"\nend V_{v.id}_e2e\n"

/-- Differential vectors: the expected bytes are produced by independent Python tooling
(`scripts/s2a.py gen-differential`, using the frozen S1 `p10tool` JCS) and checked by the kernel. -/
def d1Text : String :=
  "import P10S2Tests.Common\n\n/-! Vector D1 (S2-D1, B6 and B1). GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_D1\nopen P10S2 P10S2Tests\n\ndef claimExp : Bytes := filebytes% \"vectors/D1/claim_digest.bin\"\ndef evidenceExp : Bytes := filebytes% \"vectors/D1/evidence_digest.bin\"\n\ntheorem claim : (claimDigestV0 P10.S1.Claim.secondBit).bytes = claimExp := by decide +kernel\n\ntheorem evidence :\n    (evidenceDigestV0 (P10.Wire.evidenceTok (P10.S1.Evidence.obs false (some false)))).bytes =\n      evidenceExp := by decide +kernel\n\nend V_D1\n"

def d2Text : String :=
  "import P10S2Tests.Common\n\n/-! Vector D2 (G6-B3). GENERATED by P10S2Tests.Gen; do not edit. -/\nnamespace V_D2\nopen P10S2 P10S2Tests\n\ndef specB : Bytes := filebytes% \"profile/LeafEncodeV0_SPEC.md\"\ndef exp : Bytes := filebytes% \"vectors/D2/spec_digest.bin\"\n\ntheorem digest : (leafEncodeSpecArtifactDigestV0 specB).bytes = exp := by decide +kernel\n\nend V_D2\n"

def main (args : List String) : IO UInt32 := do
  let some mdHex := args.head? | IO.eprintln "usage: Gen <manifest-digest-hex>"; return 2
  let mdBytes := mdHex.toList.map Char.toNat
  if h : allTokB mdBytes = true then
    let md : Tok := ⟨mdBytes, h⟩
    let specBytes := (← IO.FS.readBinFile "profile/LeafEncodeV0_SPEC.md").toList.map UInt8.toNat
    let lsBytes := (P10S2.hexOf (leafEncodeSpecArtifactDigestV0 specBytes).bytes)
    let some ls : Option Tok :=
      if h2 : allTokB lsBytes = true then some ⟨lsBytes, h2⟩ else none
      | IO.eprintln "leaf spec digest is not a token"; return 2
    let mut index := "id\tprereg\tcondition\tlean\ttb7\n"
    for v in catalogue md ls do
      let dir : System.FilePath := s!"vectors/{v.id}"
      IO.FS.createDirAll dir
      writeBytes (dir / "pB.json") v.pB
      writeBytes (dir / "inst.bin") (cInstanceCommitment.enc v.inst)
      let mut tHex : Option String := none
      if let some T := v.T then
        let tB := encodeTranscript fxItemC T
        writeBytes (dir / "tB.bin") tB
        tHex := some (hexStr (sha256 tB))
      if let some iB := v.iB then writeBytes (dir / "iB.json") iB
      let tb7 := v.tb7.getD "-"
      IO.FS.writeFile (dir / "expected.txt")
        s!"id: {v.id}\nprereg: {v.prereg}\ncondition: {v.cond}\nlean: {v.expect}\ntb7: {tb7}\ne2e: {v.e2e.getD "-"}\nnote: {v.note}\n"
      IO.FS.writeFile s!"P10S2Tests/V_{v.id}.lean" (moduleText v)
      match v.iB, v.e2e, tHex with
      | some _, some ex, some h =>
        IO.FS.writeFile s!"P10S2Tests/V_{v.id}_e2e.lean" (e2eModuleText v h ex)
      | _, _, _ => pure ()
      index := index ++ s!"{v.id}\t{v.prereg}\t{v.cond}\t{v.expect}\t{tb7}\n"
    for (id, pre, txt) in [("D1", "S2-D1", d1Text), ("D2", "G6-B3 (leaf spec artifact digest)", d2Text)] do
      IO.FS.createDirAll s!"vectors/{id}"
      IO.FS.writeFile s!"vectors/{id}/expected.txt"
        s!"id: {id}\nprereg: {pre}\ncondition: differential\nlean: equal\ntb7: -\ne2e: -\nnote: expected bytes from scripts/s2a.py gen-differential\n"
      IO.FS.writeFile s!"P10S2Tests/V_{id}.lean" txt
      index := index ++ s!"{id}\t{pre}\tdifferential\tequal\t-\n"
    IO.FS.writeFile "vectors/INDEX.tsv" index
    IO.println s!"generated {(catalogue md ls).length + 2} vectors"
    return 0
  else
    IO.eprintln "manifest digest must be a token (hex)"
    return 2
