import P10S2Tests.Common

/-! Vector D1 (S2-D1, B6 and B1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_D1
open P10S2 P10S2Tests

def claimExp : Bytes := filebytes% "vectors/D1/claim_digest.bin"
def evidenceExp : Bytes := filebytes% "vectors/D1/evidence_digest.bin"

theorem claim : (claimDigestV0 P10.S1.Claim.secondBit).bytes = claimExp := by decide +kernel

theorem evidence :
    (evidenceDigestV0 (P10.Wire.evidenceTok (P10.S1.Evidence.obs false (some false)))).bytes =
      evidenceExp := by decide +kernel

end V_D1
