import P10S2Tests.Common

/-! Vector D2 (G6-B3). GENERATED by P10S2Tests.Gen; do not edit.
`formula`: the Lean definition is exactly the gated formula. `empty` and `small` are kernel differentials against independent Python (hashlib) on small inputs (1 and 2 SHA-256 blocks; the second crosses a block boundary). The digest of the real 5.7 KB spec file is checked by `scripts/s2a.py leafspec` (independent Python), not by the kernel: its size would decide whether the acceptance command fits a runner. -/
namespace V_D2
open P10S2 P10S2Tests

theorem formula (f : Bytes) :
    (leafEncodeSpecArtifactDigestV0 f).bytes =
      P10.Sha256.sha256 (bytes% "P10-LeafEncodeSpecArtifact-v0:" ++ bytes% "text-markdown-utf-8-v0:" ++ f) := rfl

def expEmpty : Bytes := filebytes% "vectors/D2/empty_digest.bin"
def expSmall : Bytes := filebytes% "vectors/D2/small_digest.bin"

theorem empty : (leafEncodeSpecArtifactDigestV0 []).bytes = expEmpty := by decide +kernel

theorem small : (leafEncodeSpecArtifactDigestV0 (bytes% "# LeafEncodeV0\n")).bytes = expSmall := by decide +kernel

end V_D2
