import P10S2Tests.Common

/-! Vector D2 (G6-B3). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_D2
open P10S2 P10S2Tests

def specB : Bytes := filebytes% "profile/LeafEncodeV0_SPEC.md"
def exp : Bytes := filebytes% "vectors/D2/spec_digest.bin"

theorem digest : (leafEncodeSpecArtifactDigestV0 specB).bytes = exp := by decide +kernel

end V_D2
