import P10S2Tests.Common

/-! Vector K2 (S2-K2, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K2
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K2/digest.bin"

theorem digest : (preclosureDigestV0 [(0, Kind.profileCommit, ⟨bytes% "owner"⟩)]).bytes = exp := by decide +kernel

end V_K2
