import P10S2Tests.Common

/-! Vector K3 (S2-K3, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K3
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K3/digest.bin"

theorem digest : (preclosureDigestV0 [(1, Kind.instanceCommit, ⟨bytes% "owner"⟩)]).bytes = exp := by decide +kernel

end V_K3
