import P10S2Tests.Common

/-! Vector K4 (S2-K4, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K4
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K4/digest.bin"

theorem digest : (preclosureDigestV0 [(2, Kind.admission, ⟨bytes% "admitter-a"⟩)]).bytes = exp := by decide +kernel

end V_K4
