import P10S2Tests.Common

/-! Vector K5 (S2-K5, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K5
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K5/digest.bin"

theorem digest : (preclosureDigestV0 [(3, Kind.closure, ⟨bytes% "owner"⟩)]).bytes = exp := by decide +kernel

end V_K5
