import P10S2Tests.Common

/-! Vector K6 (S2-K6, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K6
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K6/digest.bin"

theorem digest : (preclosureDigestV0 [(4, Kind.adjudication, ⟨bytes% "owner"⟩)]).bytes = exp := by decide +kernel

end V_K6
