import P10S2Tests.Common

/-! Vector K7 (S2-K7, K-1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K7
open P10S2 P10S2Tests

def exp : Bytes := filebytes% "vectors/K7/digest.bin"

theorem digest : (preclosureDigestV0 [(0, Kind.profileCommit, ⟨bytes% "owner"⟩), (7, Kind.instanceCommit, ⟨bytes% "owner"⟩), (10, Kind.admission, ⟨bytes% "admitter-a"⟩), (123, Kind.admission, ⟨bytes% "admitter-b"⟩)]).bytes = exp := by decide +kernel

end V_K7
