import P10S2Tests.Common

/-! Vector K8 (S2-K8): Lean `PreclosureDigestV0` on K1-K7 equals the independent Python values. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_K8
open P10S2 P10S2Tests

def views : List (List (Nat × Kind × Iss)) :=
  [[],
    [(0, Kind.profileCommit, ⟨bytes% "owner"⟩)],
    [(1, Kind.instanceCommit, ⟨bytes% "owner"⟩)],
    [(2, Kind.admission, ⟨bytes% "admitter-a"⟩)],
    [(3, Kind.closure, ⟨bytes% "owner"⟩)],
    [(4, Kind.adjudication, ⟨bytes% "owner"⟩)],
    [(0, Kind.profileCommit, ⟨bytes% "owner"⟩), (7, Kind.instanceCommit, ⟨bytes% "owner"⟩), (10, Kind.admission, ⟨bytes% "admitter-a"⟩), (123, Kind.admission, ⟨bytes% "admitter-b"⟩)]]

def exps : List Bytes := [(filebytes% "vectors/K1/digest.bin" : Bytes), (filebytes% "vectors/K2/digest.bin" : Bytes), (filebytes% "vectors/K3/digest.bin" : Bytes), (filebytes% "vectors/K4/digest.bin" : Bytes), (filebytes% "vectors/K5/digest.bin" : Bytes), (filebytes% "vectors/K6/digest.bin" : Bytes), (filebytes% "vectors/K7/digest.bin" : Bytes)]

theorem all : views.map (fun v => (preclosureDigestV0 v).bytes) = exps := by decide +kernel

end V_K8
