import P10S2Tests.Common

/-! Vector N0 (S2-N0). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N0
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N0/pB.json"
def instB : Bytes := filebytes% "vectors/N0/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N0/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c9_refsNotExactRelevantSet) := by decide +kernel

end V_N0
