import P10S2Tests.Common

/-! Vector N1 (S2-N1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N1
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N1/pB.json"
def instB : Bytes := filebytes% "vectors/N1/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N1/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c9_refsNotExactRelevantSet) := by decide +kernel

end V_N1
