import P10S2Tests.Common

/-! Vector N12 (S2-N12). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N12
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N12/pB.json"
def instB : Bytes := filebytes% "vectors/N12/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N12/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c6_noValidClosure) := by decide +kernel

end V_N12
