import P10S2Tests.Common

/-! Vector N19 (S2-N19). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N19
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N19/pB.json"
def instB : Bytes := filebytes% "vectors/N19/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N19/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileDigest) := by decide +kernel

end V_N19
