import P10S2Tests.Common

/-! Vector N13a (S2-N13 (profile commitment absent)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N13a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N13a/pB.json"
def instB : Bytes := filebytes% "vectors/N13a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N13a/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c3_noProfileCommitment) := by decide +kernel

end V_N13a
