import P10S2Tests.Common

/-! Vector N14 (S2-N14). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N14
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N14/pB.json"
def instB : Bytes := filebytes% "vectors/N14/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N14/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c5_citesNonOwnerLifecycle) := by decide +kernel

end V_N14
