import P10S2Tests.Common

/-! Vector N18 (S2-N18). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N18
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N18/pB.json"
def instB : Bytes := filebytes% "vectors/N18/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N18/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false none)) := by decide +kernel

end V_N18
