import P10S2Tests.Common

/-! Vector N10 (S2-N10). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N10
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N10/pB.json"
def instB : Bytes := filebytes% "vectors/N10/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N10/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false none)) := by decide +kernel

end V_N10
