import P10S2Tests.Common

/-! Vector N13b (S2-N13 (profile commitment after first admission)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N13b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N13b/pB.json"
def instB : Bytes := filebytes% "vectors/N13b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N13b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c3_profileAfterFirstAdmission) := by decide +kernel

end V_N13b
