import P10S2Tests.Common

/-! Vector N16 (S2-N16). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N16
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N16/pB.json"
def instB : Bytes := filebytes% "vectors/N16/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N16/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c2_rowUnavailable) := by decide +kernel

end V_N16
