import P10S2Tests.Common

/-! Vector N11 (S2-N11). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N11
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N11/pB.json"
def instB : Bytes := filebytes% "vectors/N11/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N11/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_rowsNotContiguous) := by decide +kernel

end V_N11
