import P10S2Tests.Common

/-! Vector N17 (S2-N17). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N17
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N17/pB.json"
def instB : Bytes := filebytes% "vectors/N17/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N17/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c8_refNotRelevantAdmission) := by decide +kernel

end V_N17
