import P10S2Tests.Common

/-! Vector N23c (S2-N23 (non-canonical encoding)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N23c
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N23c/pB.json"
def instB : Bytes := filebytes% "vectors/N23c/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N23c/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileDecode) := by decide +kernel

end V_N23c
