import P10S2Tests.Common

/-! Vector N24 (S2-N24 (B1)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N24
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N24/pB.json"
def instB : Bytes := filebytes% "vectors/N24/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N24/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c13_closedEvidenceDigest) := by decide +kernel

end V_N24
