import P10S2Tests.Common

/-! Vector N28a (S2-N28a (B2,B4)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N28a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N28a/pB.json"
def instB : Bytes := filebytes% "vectors/N28a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N28a/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1c_subjectDerivationDigest) := by decide +kernel

end V_N28a
