import P10S2Tests.Common

/-! Vector N23b (S2-N23 (missing field)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N23b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N23b/pB.json"
def instB : Bytes := filebytes% "vectors/N23b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N23b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileDecode) := by decide +kernel

end V_N23b
