import P10S2Tests.Common

/-! Vector N28d (S2-N28d (B4)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N28d
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N28d/pB.json"
def instB : Bytes := filebytes% "vectors/N28d/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N28d/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1c_admissionRuleDigest) := by decide +kernel

end V_N28d
