import P10S2Tests.Common

/-! Vector N22b (S2-N22 (normative_profile_digest)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N22b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N22b/pB.json"
def instB : Bytes := filebytes% "vectors/N22b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N22b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileFields) := by decide +kernel

end V_N22b
