import P10S2Tests.Common

/-! Vector N21 (S2-N21). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N21
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N21/pB.json"
def instB : Bytes := filebytes% "vectors/N21/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N21/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false none)) := by decide +kernel

end V_N21
