import P10S2Tests.Common

/-! Vector N28e (S2-N28e (B4)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N28e
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N28e/pB.json"
def instB : Bytes := filebytes% "vectors/N28e/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N28e/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1c_coverageRuleDigest) := by decide +kernel

end V_N28e
