import P10S2Tests.Common

/-! Vector N2 (S2-N2). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N2
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N2/pB.json"
def instB : Bytes := filebytes% "vectors/N2/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N2/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c7_refsNotStrictlyAscending) := by decide +kernel

end V_N2
