import P10S2Tests.Common

/-! Vector N28b (S2-N28b (B4)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N28b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N28b/pB.json"
def instB : Bytes := filebytes% "vectors/N28b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N28b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1c_leafEncodingProfileDigest) := by decide +kernel

end V_N28b
