import P10S2Tests.Common

/-! Vector N23a (S2-N23 (extra field)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N23a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N23a/pB.json"
def instB : Bytes := filebytes% "vectors/N23a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N23a/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileDecode) := by decide +kernel

end V_N23a
