import P10S2Tests.Common

/-! Vector N26 (S2-N26 (B2)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N26
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N26/pB.json"
def instB : Bytes := filebytes% "vectors/N26/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N26/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1a_ownerNotIssuer) := by decide +kernel

end V_N26
