import P10S2Tests.Common

/-! Vector N29 (S2-N29 (B3)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N29
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N29/pB.json"
def instB : Bytes := filebytes% "vectors/N29/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N29/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1b_admittersDigest) := by decide +kernel

end V_N29
