import P10S2Tests.Common

/-! Vector N22c (S2-N22 (s1_profile_token)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N22c
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N22c/pB.json"
def instB : Bytes := filebytes% "vectors/N22c/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N22c/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_profileFields) := by decide +kernel

end V_N22c
