import P10S2Tests.Common

/-! Vector N28c (S2-N28c (B4)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N28c
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N28c/pB.json"
def instB : Bytes := filebytes% "vectors/N28c/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N28c/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1c_evidenceScopeDigest) := by decide +kernel

end V_N28c
