import P10S2Tests.V_N33

/-! Vector N33 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33_dig
open P10S2 P10S2Tests V_N33

def tDigest : Bytes := hex% "b2cf272a2e221dbc01ff47cdb52e532a90334cd72668f9d8aeeaecebfe13bb0e"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_N33_dig
