import P10S2Tests.V_N33

/-! Vector N33 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33_dig
open P10S2 P10S2Tests V_N33

def tDigest : Bytes := hex% "44189dabfb5789a63bdde0b6357e3294d5c2977eff42975d5d966900ef2aa08e"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_N33_dig
