import P10S2Tests.Common

/-! Vector N3 (S2-N3). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N3
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N3/pB.json"
def instB : Bytes := filebytes% "vectors/N3/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N3/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c7_refsNotStrictlyAscending) := by decide +kernel

end V_N3
