import P10S2Tests.Common

/-! Vector N34 (S2-N34 (I-2: legacy binary preclosure digest)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N34
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N34/pB.json"
def instB : Bytes := filebytes% "vectors/N34/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N34/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c6_noValidClosure) := by decide +kernel

end V_N34
