import P10S2Tests.V_N33
import P10S2Tests.V_N33_dig

/-! Vector N33 (prereg S2-N33 (B6: withdrawn raw-token claim digest)) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33_e2e
open P10S2 P10S2Tests V_N33 V_N33_dig

def iB : Bytes := filebytes% "vectors/N33/iB.json"

def T : Transcript FxItem := (decodeTranscript fxItemC tB).get (by decide +kernel)

theorem hT : decodeTranscript fxItemC tB = some T := (Option.some_get _).symm

theorem hI : decodeInst instB = some inst := (Option.some_get _).symm

theorem hC : coverageCheck fx inst pB T = (.accept (.obs false none) : CoverageOutcome P10.S1.Evidence) := by
  have h := outcome
  unfold run at h
  rw [hI, hT] at h
  simp only [Option.bind_some] at h
  exact Option.some.inj h

theorem e2e_outcome : runE2E tDigest tB pB iB instB = none := by
  have h1 := runE2E_of_inst (tDigest := tDigest) (tB := tB) (pB := pB) (iB := iB) hI
  have h2 := e2eCheck_of_parts (iB := iB) hDig hT hC
  have h3 : (match P10.Wire.decode iB with
      | none => none
      | some si =>
        if (decide (si.evidence = (.obs false none)) && decide (claimDigestV0 si.claim = inst.claimDigest) &&
            P10.Wire.check iB) = true then some (((.obs false none) : P10.S1.Evidence), si.claim) else none) = none := by
    decide +kernel
  exact h1.trans (h2.trans h3)

end V_N33_e2e
