import P10S2Tests.Common

/-! Vector N32b (S2-N32b (B5)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N32b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N32b/pB.json"
def instB : Bytes := filebytes% "vectors/N32b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N32b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c11_adjudicationRefsMismatch) := by decide +kernel

end V_N32b
