import P10S2Tests.Common

/-! Vector N35 (S2-N35 (I-3: legacy binary key-resolution digest)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N35
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N35/pB.json"
def instB : Bytes := filebytes% "vectors/N35/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N35/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1b_keyResolutionDigest) := by decide +kernel

end V_N35
