import P10S2Tests.Common

/-! Vector N36a (S2-N36a (G6-B1)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N36a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N36a/pB.json"
def instB : Bytes := filebytes% "vectors/N36a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N36a/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c3_multipleProfileCommitments) := by decide +kernel

end V_N36a
