import P10S2Tests.Common

/-! Vector N33 (S2-N33 (B6: withdrawn raw-token claim digest)) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33_e2e
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N33/pB.json"
def instB : Bytes := filebytes% "vectors/N33/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N33/tB.bin"
def iB : Bytes := filebytes% "vectors/N33/iB.json"
def tDigest : Bytes := hex% "8a393e3b28901b7c95433ae3d4cfeea61c0a48983b9d8c0d8030d7c21b2c5649"

theorem e2e_outcome : runE2E tDigest tB pB iB instB = none := by decide +kernel

end V_N33_e2e
