import P10S2Tests.Common

/-! Vector N33 (S2-N33 (B6: withdrawn raw-token claim digest)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N33/pB.json"
def instB : Bytes := filebytes% "vectors/N33/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N33/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false none)) := by decide +kernel

end V_N33
