import P10S2Tests.Common

/-! Vector N32d (S2-N32d (B5)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N32d
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N32d/pB.json"
def instB : Bytes := filebytes% "vectors/N32d/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N32d/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c11_adjudicationRefsMismatch) := by decide +kernel

end V_N32d
