import P10S2Tests.Common

/-! Vector N31 (S2-N31 (B3: authorization without key)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N31
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N31/pB.json"
def instB : Bytes := filebytes% "vectors/N31/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N31/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c2_keyUnavailable) := by decide +kernel

end V_N31
