import P10S2Tests.Common

/-! Vector N30 (S2-N30 (B3: key without authorization)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N30
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N30/pB.json"
def instB : Bytes := filebytes% "vectors/N30/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N30/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c8_refNotRelevantAdmission) := by decide +kernel

end V_N30
