import P10S2Tests.Common

/-! Vector N36b (S2-N36b (G6-B1)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N36b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N36b/pB.json"
def instB : Bytes := filebytes% "vectors/N36b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N36b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c3_multipleProfileCommitments) := by decide +kernel

end V_N36b
