import P10S2Tests.V_N33

/-! Vector N33 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N33_dig
open P10S2 P10S2Tests V_N33

def tDigest : Bytes := hex% "e2b0c38e744b1ff33b551d1cf70a610ba5384e76fde07dda85ece6406931600e"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_N33_dig
