import P10S2Tests.Common

/-! Vector N4b (S2-N4 (uncited)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N4b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N4b/pB.json"
def instB : Bytes := filebytes% "vectors/N4b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N4b/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false none)) := by decide +kernel

end V_N4b
