import P10S2Tests.Common

/-! Vector N5 (S2-N5). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N5
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N5/pB.json"
def instB : Bytes := filebytes% "vectors/N5/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N5/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c10_relevantAdmissionAfterClosure) := by decide +kernel

end V_N5
