import P10S2Tests.Common

/-! Vector N6c (S2-N6b (conflicting commitment)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N6c
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N6c/pB.json"
def instB : Bytes := filebytes% "vectors/N6c/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N6c/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c4_multipleCommitments) := by decide +kernel

end V_N6c
