import P10S2Tests.Common

/-! Vector N6a (S2-N6a). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N6a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N6a/pB.json"
def instB : Bytes := filebytes% "vectors/N6a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N6a/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c4_noInstanceCommitment) := by decide +kernel

end V_N6a
