import P10S2Tests.Common

/-! Vector N6b (S2-N6b (two commitments)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N6b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N6b/pB.json"
def instB : Bytes := filebytes% "vectors/N6b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N6b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c4_multipleCommitments) := by decide +kernel

end V_N6b
