import P10S2Tests.Common

/-! Vector N7a (S2-N7 (payload unavailable)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N7a
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N7a/pB.json"
def instB : Bytes := filebytes% "vectors/N7a/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N7a/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c2_subjectPayloadUnavailable) := by decide +kernel

end V_N7a
