import P10S2Tests.Common

/-! Vector N7c (S2-N7 (keyUnavailable, admitter)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N7c
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N7c/pB.json"
def instB : Bytes := filebytes% "vectors/N7c/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N7c/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c2_keyUnavailable) := by decide +kernel

end V_N7c
