import P10S2Tests.Common

/-! Vector N7b (S2-N7 (checkpoint material missing)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N7b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N7b/pB.json"
def instB : Bytes := filebytes% "vectors/N7b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)

theorem outcome : runMissing pB instB = some (.halt .tb5_checkpointMaterialUnavailable) := by decide +kernel

end V_N7b
