import P10S2Tests.Common

/-! Vector N8 (S2-N8). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N8
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N8/pB.json"
def instB : Bytes := filebytes% "vectors/N8/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N8/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_logIdentity) := by decide +kernel

end V_N8
