import P10S2Tests.Common

/-! Vector N9 (S2-N9). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_N9
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/N9/pB.json"
def instB : Bytes := filebytes% "vectors/N9/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/N9/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1b_keyResolutionDigest) := by decide +kernel

end V_N9
