import P10S2Tests.V_P1

/-! Vector P1 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P1_dig
open P10S2 P10S2Tests V_P1

def tDigest : Bytes := hex% "5ce4de01073f9475cd7082e7fd7770f19533130e5fb28f6e2efe16479ab096b4"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_P1_dig
