import P10S2Tests.Common

/-! Vector P1 (S2-P1). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P1
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P1/pB.json"
def instB : Bytes := filebytes% "vectors/P1/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P1/tB.bin"

theorem outcome : run pB instB tB = some (.accept (.obs false (some false))) := by decide +kernel

end V_P1
