import P10S2Tests.V_P1
import P10S2Tests.V_P1_dig

/-! Vector P1 (prereg S2-P1) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P1_e2e
open P10S2 P10S2Tests V_P1 V_P1_dig

def iB : Bytes := filebytes% "vectors/P1/iB.json"

def T : Transcript FxItem := (decodeTranscript fxItemC tB).get (by decide +kernel)

theorem hT : decodeTranscript fxItemC tB = some T := (Option.some_get _).symm

theorem hI : decodeInst instB = some inst := (Option.some_get _).symm

theorem hC : coverageCheck fx inst pB T = (.accept (.obs false (some false)) : CoverageOutcome P10.S1.Evidence) := by
  have h := outcome
  unfold run at h
  rw [hI, hT] at h
  simp only [Option.bind_some] at h
  exact Option.some.inj h

theorem e2e_outcome : runE2E tDigest tB pB iB instB = none := by
  have h1 := runE2E_of_inst (tDigest := tDigest) (tB := tB) (pB := pB) (iB := iB) hI
  have h2 := e2eCheck_of_parts (iB := iB) hDig hT hC
  have h3 : (match P10.Wire.decode iB with
      | none => none
      | some si =>
        if (decide (si.evidence = (.obs false (some false))) && decide (claimDigestV0 si.claim = inst.claimDigest) &&
            P10.Wire.check iB) = true then some (((.obs false (some false)) : P10.S1.Evidence), si.claim) else none) = none := by
    decide +kernel
  exact h1.trans (h2.trans h3)

theorem s1_determinate : P10.Determinate P10.S1.profile (P10.S1.Evidence.obs false (some false)) P10.S1.Claim.secondBit :=
  P10.S1.none_does_not_decide_determinacy.2.2.1
theorem s1_no_certificate : ¬ Nonempty (P10.UnderdeterminationCertificate P10.S1.profile (P10.S1.Evidence.obs false (some false)) P10.S1.Claim.secondBit) :=
  P10.S1.n1_determined_no_certificate

end V_P1_e2e
