import P10S2Tests.Common

/-! Vector P1 (S2-P1) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P1_e2e
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P1/pB.json"
def instB : Bytes := filebytes% "vectors/P1/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P1/tB.bin"
def iB : Bytes := filebytes% "vectors/P1/iB.json"
def tDigest : Bytes := hex% "5e8ae91c62f0d15efcaae64c701bb54a0d9332b092f9957844f22721a6feeffe"

theorem e2e_outcome : runE2E tDigest tB pB iB instB = none := by decide +kernel

theorem s1_determinate : P10.Determinate P10.S1.profile (P10.S1.Evidence.obs false (some false)) P10.S1.Claim.secondBit :=
  P10.S1.none_does_not_decide_determinacy.2.2.1
theorem s1_no_certificate : ¬ Nonempty (P10.UnderdeterminationCertificate P10.S1.profile (P10.S1.Evidence.obs false (some false)) P10.S1.Claim.secondBit) :=
  P10.S1.n1_determined_no_certificate

end V_P1_e2e
