import P10S2Tests.V_P1

/-! Vector P1 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P1_dig
open P10S2 P10S2Tests V_P1

def tDigest : Bytes := hex% "607dab02c3ab6f15e208b333a4c3d2e008ccbfd1c9cc53565f4b8d9c5bcc1bfb"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_P1_dig
