import P10S2Tests.Common

/-! Vector P2 (S2-P2) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P2_e2e
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P2/pB.json"
def instB : Bytes := filebytes% "vectors/P2/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P2/tB.bin"
def iB : Bytes := filebytes% "vectors/P2/iB.json"
def tDigest : Bytes := hex% "369947afd7e68ff9d165e3f0b909f122b8f39e48952812fba7906e02b3b5dbba"

theorem e2e_outcome : runE2E tDigest tB pB iB instB = some (.obs false none, .secondBit) := by decide +kernel

theorem chain :
    ∃ T : Transcript fx.Item, decodeTranscript fxItemC tB = some T ∧
      (∀ V : LogView fx.Item, TranscriptFaithful T V →
        CoverageSpecV fx inst pB V (P10.S1.Evidence.obs false none)) ∧
      P10.Underdetermined P10.S1.profile (P10.S1.Evidence.obs false none) P10.S1.Claim.secondBit := by
  have hI : decodeInst instB = some inst := (Option.some_get _).symm
  have h : e2eCheck tDigest tB pB iB inst = some (P10.S1.Evidence.obs false none, P10.S1.Claim.secondBit) := by
    have h0 := e2e_outcome
    unfold runE2E at h0
    rw [hI] at h0
    simpa using h0
  obtain ⟨_, T, hT, _, _, _, _, hu, hv⟩ := e2eCheck_sound h
  exact ⟨T, hT, hv, hu⟩

end V_P2_e2e
