import P10S2Tests.V_P2

/-! Vector P2 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P2_dig
open P10S2 P10S2Tests V_P2

def tDigest : Bytes := hex% "062c663e7b9d12aba360b0db0edf9b45ac7e308de91626e7020fd6d5416ede9b"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_P2_dig
