import P10S2Tests.Common

/-! Vector P2x (S2-P2 (literal scenario, no adjudication)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P2x
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P2x/pB.json"
def instB : Bytes := filebytes% "vectors/P2x/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P2x/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c11_noAdjudicationAfterClosure) := by decide +kernel

end V_P2x
