import P10S2Tests.V_P2

/-! Vector P2 transcript digest. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P2_dig
open P10S2 P10S2Tests V_P2

def tDigest : Bytes := hex% "de143fb760f7fc97bcf05c038e071dcb73ed6e5ee18edc431cbb78651be1fb70"

theorem hDig : P10.Sha256.sha256 tB = tDigest := by decide +kernel

end V_P2_dig
