import P10S2Tests.V_P2
import P10S2Tests.V_P2_dig

/-! Vector P2 (prereg S2-P2) end-to-end. GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P2_e2e
open P10S2 P10S2Tests V_P2 V_P2_dig

def iB : Bytes := filebytes% "vectors/P2/iB.json"

def T : Transcript FxItem := (decodeTranscript fxItemC tB).get (by decide +kernel)

theorem hT : decodeTranscript fxItemC tB = some T := (Option.some_get _).symm

theorem hI : decodeInst instB = some inst := (Option.some_get _).symm

theorem hC : coverageCheck fx inst pB T = (.accept (.obs false none) : CoverageOutcome P10.S1.Evidence) := by
  have h := outcome
  unfold run at h
  rw [hI, hT] at h
  simp only [Option.bind_some] at h
  exact Option.some.inj h

theorem e2e_outcome : runE2E tDigest tB pB iB instB = some (.obs false none, .secondBit) := by
  have h1 := runE2E_of_inst (tDigest := tDigest) (tB := tB) (pB := pB) (iB := iB) hI
  have h2 := e2eCheck_of_parts (iB := iB) hDig hT hC
  have h3 : (match P10.Wire.decode iB with
      | none => none
      | some si =>
        if (decide (si.evidence = (.obs false none)) && decide (claimDigestV0 si.claim = inst.claimDigest) &&
            P10.Wire.check iB) = true then some (((.obs false none) : P10.S1.Evidence), si.claim) else none) = some (.obs false none, .secondBit) := by
    decide +kernel
  exact h1.trans (h2.trans h3)

theorem chain :
    ∃ T : Transcript fx.Item, decodeTranscript fxItemC tB = some T ∧
      (∀ V : LogView fx.Item, TranscriptFaithful T V →
        CoverageSpecV fx inst pB V (P10.S1.Evidence.obs false none)) ∧
      P10.Underdetermined P10.S1.profile (P10.S1.Evidence.obs false none) P10.S1.Claim.secondBit := by
  have hI : decodeInst instB = some inst := (Option.some_get _).symm
  have h : e2eCheck tDigest tB pB iB inst = some (P10.S1.Evidence.obs false none, P10.S1.Claim.secondBit) := by
    have h0 := e2e_outcome
    unfold runE2E at h0
    rw [hI] at h0
    simpa using h0
  obtain ⟨_, T, hT, _, _, _, _, hu, hv⟩ := e2eCheck_sound h
  exact ⟨T, hT, hv, hu⟩

end V_P2_e2e
