import P10S2Tests.Common

/-! Vector P3b (S2-P3 (closure [A1] only)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P3b
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P3b/pB.json"
def instB : Bytes := filebytes% "vectors/P3b/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P3b/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c9_refsNotExactRelevantSet) := by decide +kernel

end V_P3b
