import P10S2Tests.Common

/-! Vector P3 (S2-P3). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_P3
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/P3/pB.json"
def instB : Bytes := filebytes% "vectors/P3/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/P3/tB.bin"

theorem outcome : run pB instB tB = some (.accept P10.S1.Evidence.inconsistent) := by decide +kernel

theorem s1_cannot_certify : ¬ Nonempty (P10.UnderdeterminationCertificate P10.S1.profile P10.S1.Evidence.inconsistent P10.S1.Claim.secondBit) :=
  P10.S1.n4_no_certificate_not_determinate.1

end V_P3
