import P10S2Tests.Common

/-! Vector X1 (addition). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X1
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X1/pB.json"
def instB : Bytes := filebytes% "vectors/X1/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X1/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_admitterSetDigest) := by decide +kernel

end V_X1
