import P10S2Tests.Common

/-! Vector X10 (addition (issuer outside the token alphabet)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X10
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X10/pB.json"
def instB : Bytes := filebytes% "vectors/X10/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X10/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1a_issuerNotToken) := by decide +kernel

end V_X10
