import P10S2Tests.Common

/-! Vector X2 (addition (commitment differs from frozen inst)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X2
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X2/pB.json"
def instB : Bytes := filebytes% "vectors/X2/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X2/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c4_commitmentMismatch) := by decide +kernel

end V_X2
