import P10S2Tests.Common

/-! Vector X3 (addition (commitment after first admission)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X3
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X3/pB.json"
def instB : Bytes := filebytes% "vectors/X3/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X3/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c4_commitmentAfterFirstAdmission) := by decide +kernel

end V_X3
