import P10S2Tests.Common

/-! Vector X4 (addition (two valid closures)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X4
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X4/pB.json"
def instB : Bytes := filebytes% "vectors/X4/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X4/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c6_multipleClosures) := by decide +kernel

end V_X4
