import P10S2Tests.Common

/-! Vector X5 (addition (empty closure)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X5
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X5/pB.json"
def instB : Bytes := filebytes% "vectors/X5/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X5/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c12_evidenceOutsideE) := by decide +kernel

end V_X5
