import P10S2Tests.Common

/-! Vector X6 (addition (no closure)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X6
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X6/pB.json"
def instB : Bytes := filebytes% "vectors/X6/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X6/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c6_noValidClosure) := by decide +kernel

end V_X6
