import P10S2Tests.Common

/-! Vector X8 (addition (adjudication not owner-signed)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X8
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X8/pB.json"
def instB : Bytes := filebytes% "vectors/X8/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X8/tB.bin"

theorem outcome : run pB instB tB = some (.halt .c11_noAdjudicationAfterClosure) := by decide +kernel

end V_X8
