import P10S2Tests.Common

/-! Vector X9 (addition (owner listed in authorized_admitters)). GENERATED by P10S2Tests.Gen; do not edit. -/
namespace V_X9
open P10S2 P10S2Tests

def pB : Bytes := filebytes% "vectors/X9/pB.json"
def instB : Bytes := filebytes% "vectors/X9/inst.bin"
def inst : InstanceCommitment := (decodeInst instB).get (by decide +kernel)
def tB : Bytes := filebytes% "vectors/X9/tB.bin"

theorem outcome : run pB instB tB = some (.reject .c1_ownerInAdmitters) := by decide +kernel

end V_X9
