import P10S2.Composition

/-!
# Axiom audit (GENERATED by `scripts/s2a.py gen-audit`)

One `#print axioms` line per non-private theorem of the checker library. The acceptance
command requires this file to be exactly up to date and every line to report only the
permitted axioms of `profile/AXIOM_POLICY.md`.
-/

#print axioms P10S2.Codec.decNatAux_rep
#print axioms P10S2.Codec.decNatAux_inv
#print axioms P10S2.Codec.decListN_rt
#print axioms P10S2.Codec.decListN_eq
#print axioms P10S2.Codec.decodeAll_enc
#print axioms P10S2.Codec.enc_decodeAll
#print axioms P10S2.s2_end_to_end
#print axioms P10S2.p10Verdict_halt
#print axioms P10S2.p10Verdict_reject
#print axioms P10S2.p10Verdict_some
#print axioms P10S2.coverage_halt_no_verdict
#print axioms P10S2.unavailable_row_no_verdict
#print axioms P10S2.unavailable_payload_no_verdict
#print axioms P10S2.e2eCheck_sound
#print axioms P10S2.unavailable_key_no_verdict
#print axioms P10S2.missing_checkpoint_halts
#print axioms P10S2.e2eCheck_none_of_not_accept
#print axioms P10S2.e2eCheck_halt_none
#print axioms P10S2.e2eCheck_reject_none
#print axioms P10S2.mem_idx_pairs
#print axioms P10S2.strictAscNat_pairwise
#print axioms P10S2.beforeAll_spec
#print axioms P10S2.finish_stage
#print axioms P10S2.coreCheck_sound
#print axioms P10S2.coverage_sound
#print axioms P10S2.matchIdxs_mem
#print axioms P10S2.inj_on_of_nodup_map'
#print axioms P10S2.viewT_eq_subj
#print axioms P10S2.coverage_sound_view
#print axioms P10S2.fx_projection
#print axioms P10S2.bundle_truth_nil
#print axioms P10S2.bundle_truth_second
#print axioms P10S2.bundle_truth_eU
#print axioms P10S2.bundle_truth_eD
#print axioms P10S2.bundle_truth_first_conflict
#print axioms P10S2.bundle_truth_second_conflict
#print axioms P10S2.bundle_truth_second_conflict_nofirst
#print axioms P10S2.faithful_core
#print axioms P10S2.mkEv_inE
#print axioms P10S2.forall_mem_iff
#print axioms P10S2.bundle_faithful
#print axioms P10S2.fxBundle_of_mem_iff
#print axioms P10S2.bundle_perm
#print axioms P10S2.mem_eraseDups_aux
#print axioms P10S2.bundle_dedup
#print axioms P10S2.bundle_refines
#print axioms P10S2.readTok_append
#print axioms P10S2.readTok_inv
#print axioms P10S2.tailEnc_len_pos
#print axioms P10S2.decTail_rt
#print axioms P10S2.decTail_eq
#print axioms P10S2.entryC_first
#print axioms P10S2.elemC_first
#print axioms P10S2.decode_encode_profile
#print axioms P10S2.encode_decode_profile
#print axioms P10S2.decode_encode_transcript
#print axioms P10S2.encode_decode_transcript
